import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import VideoProvider from "@/context/video-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Power Hour Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="sunset">
      <body className={inter.className}>
        <VideoProvider>{children}</VideoProvider>
      </body>
    </html>
  );
}
